import AppLayout from '@/components/Layouts/AppLayout';
import Head from 'next/head';
import BackButton from '@/components/BackButton';
import Input from '@/components/Input';
import Button from '@/components/Button';
import { useForm } from 'react-hook-form';
import { useDispatch, useSelector } from '@/store';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import toast from 'react-hot-toast';
import * as Yup from 'yup';
import { yupResolver } from '@hookform/resolvers/yup';
import Label from '@/components/Label';
import Toggle from '@/components/Toggle';
import { getLanguage, updateLanguage } from '@/store/slices/language';

Edit.getLayout = page => <AppLayout name="Edit">{page}</AppLayout>;

const LanguageUpdateSchema = Yup.object().shape({
    is_active: Yup.boolean(),
    name: Yup.string().required('Required'),
    code: Yup.string().required('Required'),
});
export default function Edit() {
    const router = useRouter();
    const { id } = router.query;

    const dispatch = useDispatch();

    const { language } = useSelector(state => state.language);

    const onSubmit = data => {
        dispatch(updateLanguage(id, data))
            .then(() => {
                toast.success('Updated successfully!');
            })
            .catch(err => {
                toast.error(err?.response?.data?.message);
                console.log(err);
            });
    };

    const {
        register,
        handleSubmit,
        formState: { errors },
    } = useForm({
        resolver: yupResolver(LanguageUpdateSchema),

        defaultValues: {
            ...language,
        },
        values: {
            ...language,
        },
    });

    useEffect(() => {
        if (!id) return;
        dispatch(getLanguage(id));
    }, [dispatch, id]);

    return (
        <>
            <Head>
                <title>Edit - İmtihan</title>
                <meta name="description" content="Generated by codenteq" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="px-4 pt-16">
                <BackButton href="/admin/language" />

                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className="flex items-center justify-between my-4">
                        <div className="mt-3">
                            <label className="inline-flex items-center">
                                <Toggle
                                    type="checkbox"
                                    {...register('is_active')}
                                    defaultValue={1}
                                />
                                {/*TODO: Fix this*/}
                                <span className="ml-2 text-sm text-zinc-600">
                                    Checked for active
                                </span>
                            </label>
                        </div>
                        <Button type="submit">Save</Button>
                    </div>
                    <div className="grid gap-4 mb-6 lg:grid-cols-2">
                        <div>
                            <Label>Name</Label>

                            <Input
                                {...register('name')}
                                type="text"
                                className="block mt-1 w-full"
                            />
                            {errors.name?.message && (
                                <p className="mt-2 text-sm text-red-600 dark:text-red-500">
                                    {errors.name.message}
                                </p>
                            )}
                        </div>
                        <div>
                            <Label>Code</Label>

                            <Input
                                {...register('code')}
                                type="text"
                                className="block mt-1 w-full"
                            />
                            {errors.code?.message && (
                                <p className="mt-2 text-sm text-red-600 dark:text-red-500">
                                    {errors.code.message}
                                </p>
                            )}
                        </div>
                    </div>
                </form>
            </main>
        </>
    );
}
