version: "3.9"

services:
  app:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped
