import AppLayout from '@/components/Layouts/AppLayout';
import Head from 'next/head';
import BackButton from '@/components/BackButton';
import Input from '@/components/Input';
import Button from '@/components/Button';
import InputSelect from '@/components/InputSelect';
import InputFile from '@/components/InputFile';
import { useForm } from 'react-hook-form';
import { useDispatch } from '@/store';
import { postCompany } from '@/store/slices/company';

Create.getLayout = page => <AppLayout name="Create">{page}</AppLayout>;
export default function Create() {
    const { register, handleSubmit } = useForm();

    const dispatch = useDispatch();
    const onSubmit = data => {
        dispatch(postCompany(data))
            .then(res => {
                console.log(res);
            })
            .catch(err => {
                console.log(err);
            });
    };

    return (
        <>
            <Head>
                <title>Create - İmtihan</title>
                <meta name="description" content="Generated by codenteq" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="px-4 pt-16">
                <BackButton href="/admin/company" />

                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className="flex items-center justify-between my-4">
                        <div className="mt-3">
                            <label className="inline-flex items-center">
                                <Input
                                    type="checkbox"
                                    {...register('is_active')}
                                    className="rounded w-2 h-2 border-brand text-brand shadow-sm focus:ring focus:ring-brand focus:ring-opacity-20"
                                />

                                <span className="ml-2 text-sm text-gray-600">
                                    Checked for active
                                </span>
                            </label>
                        </div>
                        <Button type="submit">Save</Button>
                    </div>
                    <InputFile className="my-4">
                        <Input
                            {...register('logo')}
                            type="file"
                            className="hidden"
                        />
                    </InputFile>
                    <div className="grid gap-4 mb-6 lg:grid-cols-2">
                        <div>
                            <Input
                                {...register('name')}
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Name"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('email')}
                                type="email"
                                className="block mt-1 w-full"
                                placeholder="Email"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('phone')}
                                type="phone"
                                className="block mt-1 w-full"
                                placeholder="Phone"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('tax_id')}
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Tax id"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('subdomain')}
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Subdomain"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('web_url')}
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Web url"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('address')}
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Address"
                            />
                        </div>
                        <div>
                            <Input
                                {...register('zip_code')}
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Zip code"
                            />
                        </div>
                        <div>
                            <InputSelect
                                {...register('country_id')}
                                defaultOption="Choose a country">
                                <option value="1">Türkiye</option>
                            </InputSelect>
                        </div>
                        <div>
                            <InputSelect
                                {...register('city_id')}
                                defaultOption="Choose a city">
                                <option value="41">Adana</option>
                            </InputSelect>
                        </div>
                        <div>
                            <InputSelect
                                {...register('state_id')}
                                defaultOption="Choose a state">
                                <option value="21">Merkez</option>
                            </InputSelect>
                        </div>
                    </div>
                </form>
            </main>
        </>
    );
}
