import AppLayout from '@/components/Layouts/AppLayout';
import Head from 'next/head';
import { useEffect } from 'react';
import Table from '@/components/Table/Table';
import NavLink from '@/components/NavLink';
import Link from 'next/link';
import { useDispatch, useSelector } from '@/store';
import { getCompanies } from '@/store/slices/company';
import { PencilIcon } from '@heroicons/react/20/solid';
import { TrashIcon } from '@heroicons/react/24/solid';

Index.getLayout = page => <AppLayout name="Companies">{page}</AppLayout>;
export default function Index() {
    const dispatch = useDispatch();

    const { companies } = useSelector(state => state.company);

    useEffect(() => {
        dispatch(getCompanies());
    }, [dispatch]);

    return (
        <>
            <Head>
                <title>Companies - İmtihan</title>
                <meta name="description" content="Generated by codenteq" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="px-4 pt-16">
                <Table
                    searchable={true}
                    head={[
                        { name: 'Şirket Adı', sortable: true },
                        { name: 'E-mail' },
                        { name: 'phone', sortable: true },
                        { name: 'İşlemler', width: 200 },
                    ]}
                    data={companies}
                />
            </main>
        </>
    );
}
