import AppLayout from '@/components/Layouts/AppLayout';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Table from '@/components/Table/Table';
import { useDispatch, useSelector } from '@/store';
import { getCompanies } from '@/store/slices/company';

Index.getLayout = page => <AppLayout name="Companies">{page}</AppLayout>;

const columns = [
    {
        Header: 'Şirkey Adı',
        accessor: 'name',
    },
    {
        Header: 'E-mail',
        accessor: 'email',
    },
    {
        Header: 'Phone',
        accessor: 'phone',
    },
];

export default function Index() {
    const dispatch = useDispatch();
    const [pagePaginate, setPagePaginate] = useState(1);

    const { companies, meta } = useSelector(state => state.company);

    useEffect(() => {
        dispatch(getCompanies(pagePaginate));
    }, [dispatch, pagePaginate]);

    return (
        <>
            <Head>
                <title>Companies - İmtihan</title>
                <meta name="description" content="Generated by codenteq" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="px-4 pt-16">
                <Table
                    columns={columns}
                    data={companies}
                    pagePaginate={pagePaginate}
                    setPagePaginate={setPagePaginate}
                    meta={meta}
                />
            </main>
        </>
    );
}
