import AppLayout from '@/components/Layouts/AppLayout';
import Head from 'next/head';
import BackButton from '@/components/BackButton';
import Input from '@/components/Input';
import Button from '@/components/Button';
import { useForm } from 'react-hook-form';
import { useDispatch, useSelector } from '@/store';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import toast from 'react-hot-toast';
import * as Yup from 'yup';
import { yupResolver } from '@hookform/resolvers/yup';
import Label from '@/components/Label';
import {
    getAnnouncement,
    updateAnnouncement,
} from '@/store/slices/announcement';
import InputFile from '@/components/InputFile';
import Textarea from '@/components/Textarea';
import Image from 'next/image';
import createImageUrl from '@/lib/image';

Edit.getLayout = page => <AppLayout name="Edit">{page}</AppLayout>;

const AnnouncementUpdateSchema = Yup.object().shape({
    name: Yup.string().required('Required'),
    content: Yup.string().required('Required'),
    src: Yup.mixed().test('src', 'You need to provide a file', value => {
        if (value.length > 0) {
            return true;
        }
        return false;
    }),
});
export default function Edit() {
    const router = useRouter();
    const { id } = router.query;

    const dispatch = useDispatch();

    const { announcement } = useSelector(state => state.announcement);
    const onSubmit = data => {
        const formData = new FormData();

        if (typeof data.src[0] === 'object') {
            formData.append('src', data.logo[0]);
        }

        for (const key in data) {
            if (key !== 'src') {
                formData.append(key, data[key]);
            }
        }

        dispatch(updateAnnouncement(id, formData))
            .then(() => {
                toast.success('Updated successfully!');
            })
            .catch(err => {
                toast.error(err?.response?.data?.message);
                console.log(err);
            });
    };

    const {
        register,
        reset,
        handleSubmit,
        formState: { errors },
    } = useForm({
        resolver: yupResolver(AnnouncementUpdateSchema),

        defaultValues: {
            ...announcement,
        },
        values: {
            ...announcement,
        },
    });

    useEffect(() => {
        if (!id) return;
        dispatch(getAnnouncement(id));
    }, [dispatch, id]);

    return (
        <>
            <Head>
                <title>Edit - İmtihan</title>
                <meta name="description" content="Generated by codenteq" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="px-4 pt-16">
                <BackButton href="/admin/announcement" />

                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className="flex items-center justify-between my-4">
                        <div className="mt-3" />
                        <Button type="submit">Save</Button>
                    </div>

                    <Label className="mr-4">Uploaded file</Label>

                    <Image
                        src={createImageUrl(announcement?.src)}
                        height={150}
                        width={150}
                        className="object-fill rounded-lg"
                    />

                    <div className="mb-3">
                        <InputFile className="my-4">
                            <Input
                                {...register('src')}
                                type="file"
                                className="hidden"
                            />
                        </InputFile>
                        {errors.src?.message && (
                            <p className="mt-2 text-sm text-red-600 dark:text-red-500">
                                {errors.src.message}
                            </p>
                        )}
                    </div>

                    <div>
                        <Label>Name</Label>

                        <Input
                            {...register('name')}
                            type="text"
                            className="block mt-1 w-full"
                        />
                        {errors.name?.message && (
                            <p className="mt-2 text-sm text-red-600 dark:text-red-500">
                                {errors.name.message}
                            </p>
                        )}
                    </div>
                    <div>
                        <Label>Content</Label>

                        <Textarea
                            {...register('content')}
                            className="block mt-1 w-full"
                        />
                        {errors.content?.message && (
                            <p className="mt-2 text-sm text-red-600 dark:text-red-500">
                                {errors.content.message}
                            </p>
                        )}
                    </div>
                </form>
            </main>
        </>
    );
}
