import AppLayout from '@/layouts/AppLayout';
import Head from 'next/head';
import { getCompany } from '@/store/slices/company';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from '@/store';
import Image from 'next/image';
import createImageUrl from '@/lib/image';
import BackButton from '@/components/BackButton';

Index.getLayout = page => <AppLayout name="View">{page}</AppLayout>;
export default function Index() {
    const router = useRouter();
    const { id } = router.query;
    const { company, isLoading } = useSelector(state => state.company);
    const dispatch = useDispatch();

    useEffect(() => {
        if (id) {
            dispatch(getCompany(id));
        }
    }, [dispatch, id]);
    return (
        <>
            <Head>
                <title>Companies - İmtihan</title>
                <meta name="description" content="Generated by codenteq" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="px-4 pt-16">
                <BackButton href="/admin/company" />

                <div className="bg-zinc-50 rounded-xl p-8 dark:bg-zinc-900">
                    {isLoading ? (
                        <div role="status" className="max-w-sm animate-pulse">
                            <div className="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-24 h-24 mb-4" />
                            <div className="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4" />
                            <div className="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5" />
                            <div className="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5" />
                            <div className="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[330px] mb-2.5" />
                            <div className="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[300px] mb-2.5" />
                            <div className="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px]" />
                        </div>
                    ) : (
                        <figure className="md:flex rounded-xl md:p-0">
                            <div className="pt-6 md:p-8 text-center md:text-left space-y-4">
                                <div className="flex justify-center md:justify-start">
                                    <Image
                                        src={createImageUrl(company?.logo)}
                                        width={96}
                                        height={96}
                                        className="border rounded-full"
                                    />
                                </div>
                                <figcaption className="font-medium">
                                    <div className="text-brand dark:text-sky-400">
                                        {company?.name}
                                    </div>
                                    <div className="text-slate-700 dark:text-slate-500">
                                        {company?.email}
                                    </div>
                                </figcaption>
                                <div>
                                    <div className="text-slate-700 dark:text-slate-500">
                                        {company?.address} {company?.zip_code}{' '}
                                        {company?.country_id.name},{' '}
                                        {company?.city_id.name},{' '}
                                        {company?.state_id.name}
                                    </div>
                                    <div className="text-slate-700 dark:text-slate-500">
                                        {company?.phone}
                                    </div>
                                    <div className="text-slate-700 dark:text-slate-500">
                                        {company?.tax_id}
                                    </div>
                                    <div className="text-slate-700 dark:text-slate-500">
                                        {company?.web_url}
                                    </div>
                                    <div className="text-slate-700 dark:text-slate-500">
                                        {company?.subdomain}
                                    </div>
                                </div>
                            </div>
                        </figure>
                    )}
                </div>
            </main>
        </>
    );
}
